# Declare global variables for package check
globalVariables(
  c(
    ".data", ":=", "AdminToClean", "Algorithm", "Distance", "MatchRank",
    "MatchedNames", "X", "country", "district_prepped", "district",
    "province_prepped", "country_prepped", "long_geo",
    "dot_name", "joined_adm", "level", "matches", "name_alias", "replacement",
    "name_corrected", "name_corrected2", "province", "_id", "matched_names",
    "date_last_updated", "form_id", "form_id_num", "last_date_in_chunk", "x",
    "ADM0_NAME", "ADM1_NAME", "ADM2_NAME", "name_to_match", "match_rank",
    "algorithm_name", "created_time", "distance", "name_of_creator",
    "level0_prepped", "level1_prepped", "level2_prepped", "log_message",
    "longname_corrected", "longname_to_match", "log_results", "lat_precision",
    "CENTER_LAT", "CENTER_LON", "ENDDATE", "low_precision", "lon_precision",
    "dist_correct", "dist_flipped", "flipped", "temp_lat", "temp_lon",
    "new_columns", "new_rows", "total_columns", "total_rows", "key_order",
    "check_on_water", "httpcode", "missing_coords", "on_water", "current_year",
    "potentially_flipped", "total_coords", "priority", "out_of_bounds",
    "coord_diff_correct", "coord_diff_input", "missing_count",
    "Column", "Is Completely Null", "Missing Count", "Missing Percent",
    "Priority column", "column", "Priority", "non_unique_count",
    "proportion_unique", "total_count", "unique_count",
    "Data_Value", "Geo_Column", "Missing_in_Shapefile",
    "DataType", "VDPV1", "VDPV2", "VdpvClassifications", "WILD1",
    "geo_id_cols", "geo_name_cols", "header", "Missing in Shapefile",
    "Non-unique Count", "Variable", "ID", "Test", "Value", "null_count",
    "Lat_parzer", "Long_parzer", "parse_failed", "parsed_date", "parsed_date1",
    "parsed_date2", "Total", "snapshot", "WHO_REGION",
    "EPID", "ParalysisOnsetDate", "Validation Type", "WPV1", "afp_cases1",
    "afp_cases2", "cVDPV1", "cVDPV2", "n_data1", "n_data2", "val_type",
    "virus_type", "CollectionDate", "Admin0Name", "Admin1Name",
    "Admin2Name", "Detections", "Emergence/Cluster Group", "NtChanges",
    "Previous Detection", "SurveillanceTypeName", "VdpvEmergenceGroupName",
    "VirusDate", "VirusTypeName", "WildClusterName",
    "Days Since Last Detections", "BaseVdpvEmergenceGroup",
    "New Emergence", "unique_emerg_grp", "ActivityDateFrom",
    "ActivityStatus", "Country", "Date of Any Last SIA Campagin",
    "Days Since SIA and Detection", "Days between
     Previous and Most Recent Detection", "level3_prepped", "level4_prepped",
    "Delayed Reporting Detections to Confirmation (days)", "Emergence Group",
    "Emergence Group", "Last SIA Date", "Most Recent Detection",
    "MostRecentVirusDate", "New VDPV Class", "New VDPV Classification",
    "Nt Changes", "Nt Changes from Closest Match", "Ntchanges",
    "VDPV Classification Change Date", "Vaccine Origin",
    "Vaccine Type", "VaccineOrigin", "VdpvClassificationChangeDate",
    "VdpvNtChangesClosestMatch", "VdpvNtChangesFromSabin",
    "VdpvReportedToHQDate", "Virus", "Virus Reported to HQ Date",
    "new_epids", "ActivityVaccineType", "Days to Confirm",
    "Days between Previous and Most Recent Detection",
    "Delayed Reporting", "Delayed Report", "level4",'EntityType',
    "Detections to Confirmation (days)", "ADM3_NAME", 
    "ADM4_NAME", "date_categ", "end", "label", "start",
    "ClusterID", "as.dist", "cutree", "dist", "hclust", "round_group"
  )
)
